### ISSUE TITLE
SublimeText does not trigger citation key completion (BibLatex, Ubuntu)

### ISSUE THREAD

**Issue by AdriaJ** [SublimeText/LaTeXTools#1605]
Hi,
I reinstalled my latex distribution on my Ubuntu machine (20.04.6 LTS). Since then, I have a problem with the autocompletion of the citation keys. When I type any citation command in my tex file ( so \cite{}, \parencite{} or \textcite{}) , the search bar does not trigger for the citation key. That is not the case when I type in-document citation with the command \ref{}. I don;t really know what to do, I verified the settings of LaTeXTools and everything is fine (including `"cite_auto_trigger": true`  ).

My document has a particular structure.

```
manuscript
│   main.tex
│   references.bib    
│
└───styles
│   │   style.sty
│   │   cmds.sty
│   
└───body
    │   chapter1.tex
    │   chapter2.tex
```

In particular, the biblatex package is loaded in the file ```style.sty``` with

```
\usepackage[
    backend=biber,
    style=authoryear,
    natbib=true,
    maxcitenames=2,
    mincitenames=1,
    giveninits=true,
    uniquename=init,
    sortlocale=en_US,
    url=false, 
    doi=true,
    eprint=false,
    isbn=false,
    backref=true
]{biblatex}
\addbibresource{references.bib}
```

and the `main.tex` file includes

```
\usepackage{styles/style}
\usepackage{styles/cmds}
```

If anyone has an idea on that!

**Comment by deathaxe** [comment]
Citation completions don't rely on latex distributions.

Completions work fine on my end with given folder structure using LaTeXTools v4.2.2.

![Image](https://github.com/user-attachments/assets/83cf07e8-76e5-4af2-a362-a76409760e0c)

- main.tex

   ```latex
   \documentclass[a4paper]{article}
   
   \usepackage{styles/style}
   
   \begin{document}
   \include{body/chapter1}
   \end{document}
   ```

- references.bib
   
   ```bibtex
   @article{myarticle,
       author = {Foo Bar},
       title = {My Article Title},
       journaltitle = {Journaltitle},
       year = {1945}
   }
   ```

- body/chapter1.tex
   ```latex
   %!TEX root=../main.tex
   
   
   This is \cite{myarticle}

   ```

- styles/style.sty

   ```latex
   \ProvidesClass{style}
   \usepackage[
       backend=biber,
       style=authoryear,
       natbib=true,
       maxcitenames=2,
       mincitenames=1,
       giveninits=true,
       uniquename=init,
       sortlocale=en_US,
       url=false, 
       doi=true,
       eprint=false,
       isbn=false,
       backref=true
   ]{biblatex}
   \addbibresource{references.bib}
   ```

**Comment by AdriaJ** [comment]
Thanks a lot for trying to reproduce my setting! It seems to work well in your case...

I don't know how to check my LaTeXTools version, but when I try to upgrade the packages with Sublime everything is up to date so I guess I have the last version.

If I write a cite command, for instance `\cite{}` and press `Ctrl + Space` I get an autocompletion menu in which I can find some cite keys however they are not tagged with a _b_ on the left (as in your screencapture) but with a _t_. I don't know what this means.

**Comment by deathaxe** [comment]
> I don't know how to check my LaTeXTools version ...

see: https://github.com/SublimeText/LaTeXTools/issues/1606

> I get an autocompletion menu in which I can find some cite keys ...

Maybe word completions automatically picked from existing cite commands. The `t` symbol would require a symbol definition for cite keys like the one from https://github.com/sublimehq/Packages/pull/4137.

Does ST's console contain any error messages? LaTeXTools should add an error log if it doesn't find bibfiles or fails parsing one.

A known "limitation" is bibfiles being rejected if entries don't have a key entry (e.g. `@article{, ...}` wouldn't work).

**Comment by AdriaJ** [comment]
Thank for the pointers.
I don't have any error in the log. I only have a couple of unsignificant warnings. The pdf produced has the perfect biography as expected.

**Comment by AdriaJ** [comment]
i stumbled across my Sublime overall settings and discovered this:
File: `/home/jarret/.config/sublime-text/Packages/User/Preferences.sublime-settings`

```
{
	"color_scheme": "Mariana.sublime-color-scheme",
	"theme": "auto",
	"ignored_packages":
	[
		"Vintage",
	],
	"index_files": true,
	"font_size": 13,
	"auto_complete_triggers":
	[
		{
			"characters": "<",
			"selector": "text.html, text.xml",
		},
		{
			"rhs_empty": true,
			"selector": "punctuation.accessor",
		},
		{
			"characters": "\\",
			"selector": "text.tex.latex",
		}
	]
}
```

**Comment by deathaxe** [comment]
I don't think so. LaTeXTools adds the `\\` pattern so command completions pop up automatically when typing `\`. 

When typing `{` after `\cite` quick panel with all bibliography entries linked with a document should pop-up. That's handled by a custom key-binding. To verify that binding being intact ...

1. open ST's console
2. execute `sublime.log_commands()`
3. type `{` after `\cite` in a tex document.

It should print something like:

```
command: latextools_fill_all {"completion_type": "cite", "insert_char": "{"}
LaTeXTools [DEBUG]: TEX root: C:\Data\LaTeX\test-1605\main.tex
LaTeXTools [DEBUG]: Bib files found:
  ('C:\\Data\\LaTeX\\test-1605\\references.bib',)
LaTeXTools [INFO]: Found 1 total bib entries
```

Note: You can also set `"log_level": "debug"` in LaTeXTools.sublime-settings to get some more detailed information about loaded bibfiles.

Maybe also check your LaTeXTools settings in general. Old LaTeXTools used to copy all defaults to user settings, which is no longer needed (nor recommended). Maybe one of those settings (if exist) augments a required default or no longer valid value (just guessing).

**Comment by AdriaJ** [comment]
Very nice! It seems that I have a Python error there:

```
command: latextools_fill_all {"completion_type": "cite", "insert_char": "{"}
LaTeXTools [DEBUG]: TEX root: /home/jarret/Documents/EPFL/PhD/thesis/manuscript/main.tex
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 1636, in run_
    return self.run(edit, **args)
  File "/home/jarret/.config/sublime-text/Packages/LaTeXTools/latextools/latex_fill_all.py", line 969, in run
    reraise(*sys.exc_info())
  File "/home/jarret/.config/sublime-text/Packages/LaTeXTools/latextools/latex_fill_all.py", line 30, in reraise
    raise value
  File "/home/jarret/.config/sublime-text/Packages/LaTeXTools/latextools/latex_fill_all.py", line 966, in run
    completions = completion_type.get_completions(view, prefix, line[::-1])
  File "/home/jarret/.config/sublime-text/Packages/LaTeXTools/latextools/latex_cite_completions.py", line 508, in get_completions
    completions = get_cite_completions(view)
  File "/home/jarret/.config/sublime-text/Packages/LaTeXTools/latextools/latex_cite_completions.py", line 430, in get_cite_completions
    bib_files = find_bib_files(root)
  File "/home/jarret/.config/sublime-text/Packages/LaTeXTools/latextools/latex_cite_completions.py", line 287, in find_bib_files
    result = set(additional_file) + set(result)
TypeError: unsupported operand type(s) for +: 'set' and 'set'
```

I remember that I had put my `.bib` file as an additional bib resource in the latextools settings. I have just removed it and now it works, thanks a lot!

```
command: latextools_fill_all {"completion_type": "cite", "insert_char": "{"}
LaTeXTools [DEBUG]: TEX root: /home/jarret/Documents/EPFL/PhD/thesis/manuscript/main.tex
LaTeXTools [DEBUG]: Bib files found:
  ('/home/jarret/Documents/EPFL/PhD/thesis/manuscript/references.bib',)
LaTeXTools [INFO]: Loaded 93 bibitems
LaTeXTools [INFO]: Found 93 total bib entries
```

I still don't know why it did not work in the first place but that's not important. You may want to fix file `LaTeXTools/latextools/latex_cite_completions.py`, line 287, with the operator `|` instead of `+` to make the union of two sets.

Once again, thank you very much for your time!

**Comment by rafael-copat** [comment]
I had a similar issue. I usually keep several lines with `\addbibresource{}` for my `.bib` files. Before LaTeXTools v.4, there was no issue if one of those files was missing. However, after LaTeXTools v.4, I get an error, so I had to comment out the lines that do not contain the files.

**Comment by deathaxe** [comment]
Fixed by v4.2.3

**Comment by kaichunf** [comment]
> That's a different issue, which is fixed by [42898ac](https://github.com/SublimeText/LaTeXTools/commit/42898acfa23f82a7213fda5a1617b794c800fa36).
> 
> v4.3.0 is already released, but not picked up by Package Control, yet.

Thank you. I just made that change to the "traditional_bibliography.py" file. Now it doesn't trigger the error, but the citation key recommendations still doesn't show up as it was previously.

**Comment by deathaxe** [comment]
1. Try cleaning up your user settings (LaTeXTools.sublime-settings), keeping only what you really want to customize. Some settings changed in structure, which could cause issues.

   Earlier versions copied all defaults to user settings, which is no longer recommended.

2. Try to _LaTeXTools: Clear Cache_ via command palette to ensure out-dated analysis cache doesn't cause any issues.

3. You can set `"log_level": "debug"` in latextools.sublime-settings to enable verbose console logs, which may provide info why citation is not working.

**Comment by kaichunf** [comment]
> 1. Try cleaning up your user settings (LaTeXTools.sublime-settings), keeping only what you really want to customize. Some settings changed in structure, which could cause issues.
>    Earlier versions copied all defaults to user settings, which is no longer recommended.
> 2. Try to _LaTeXTools: Clear Cache_ via command palette to ensure out-dated analysis cache doesn't cause any issues.
> 3. You can set `"log_level": "debug"` in latextools.sublime-settings to enable verbose console logs, which may provide info why citation is not working.

I tried _LaTeXTools: Clear Cache_, didn't work... 

After setting the log_level to debug, this is what it gave me: 

```bash
LaTeXTools [DEBUG]: Bib files found:
  ('<TexRoot directory>\\references.bib',)
LaTeXTools [INFO]: Found 0 total bib entries
```
But the thing is that I have a completely legit .bib file...

**Comment by deathaxe** [comment]
Yet another typo in traditional bibliography parser. Fixed by https://github.com/SublimeText/LaTeXTools/commit/4d657c8838883d372d9e24aab936e25c781c572e.

**Comment by kaichunf** [comment]
> Yet another typo in traditional bibliography parser. Fixed by [4d657c8](https://github.com/SublimeText/LaTeXTools/commit/4d657c8838883d372d9e24aab936e25c781c572e).

Thank you, it is finally working! 

But the first build after a clear of the cache didn't go smoothly. This is what I got: 

```bash
LaTeXTools [INFO]: Found 190 total bib entries
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1636, in run_
    return self.run(edit, **args)
  File "C:\Users\fukai\AppData\Roaming\Sublime Text\Packages\LaTeXTools\latextools\latex_fill_all.py", line 969, in run
    reraise(*sys.exc_info())
  File "C:\Users\fukai\AppData\Roaming\Sublime Text\Packages\LaTeXTools\latextools\latex_fill_all.py", line 30, in reraise
    raise value
  File "C:\Users\fukai\AppData\Roaming\Sublime Text\Packages\LaTeXTools\latextools\latex_fill_all.py", line 966, in run
    completions = completion_type.get_completions(view, prefix, line[::-1])
  File "C:\Users\fukai\AppData\Roaming\Sublime Text\Packages\LaTeXTools\latextools\latex_cite_completions.py", line 540, in get_completions
    trigger=result[0], details=result[1:] or "", annotation=keyword, kind=kind
TypeError: 'generator' object is not subscriptable
command: drag_select {"event": {"button": 1, "x": 534.5, "y": 895.5}}
command: drag_select {"event": {"button": 1, "x": 
```

Starting from the second build, everything works out fine...

**Comment by deathaxe** [comment]
Pushed 2 more commits to fix the TypeError and another race condition caused by storing new cache entries.
