### ISSUE TITLE
Mac OS El Capitan - Compile Fails

### ISSUE THREAD

**Issue by ankmathur96** [SublimeText/LaTeXTools#531]
I use Sublime Text 3, and I recently reinstalled LatexTools for ST3, so my install is up to date by the current instructions posted online.

After updating to the public beta of Mac OS X El Capitan, when trying to compile a document, I got the following output:

TraditionalBuilder: Invoking latexmk... 

COULD NOT COMPILE!

Attempted command:latexmk -cd -e $pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %S %O' -f -pdf resume.tex
Build engine: Traditional Builder

I understand that it's a public beta, and you're definitely not required to support it off the bat, but I just wanted to put this up so you're aware of it. Please let me know if you need more information.

**Comment by kenohori** [comment]
If you just upgraded to El Capitan, this can be easily fixed by first running Setup-2015.pkg to reconfigure MacTeX 2015, then replacing /usr/texbin with /Library/TeX/texbin in the LaTeXTools configuration.

**Comment by ankmathur96** [comment]
Worked. Thanks!

**Comment by ahmadassaf** [comment]
Hello, any clue why i still get this error. I did change the path, it works perfectly from the terminal but still get the error when trying to build from Sublime

**Comment by ahmadassaf** [comment]
i just had to install the full installer not the mini version. Works great now :+1:

**Comment by TempSpas** [comment]
> replacing /usr/texbin with /Library/TeX/texbin in the LaTeXTools configuration

I assume this meant to change ```"texpath" : "$PATH:/ /usr/texbin:/usr/local/bin:/opt/local/bin"``` to ```"texpath" : "$PATH:/Library/TeX/texbin:/usr/local/bin:/opt/local/bin"``` in the ```LaTeXTools Preferences.sublime-settings``` file. If that's the case, I have done that and am getting the same error as the OP still. Can anyone provide input?

**Comment by TempSpas** [comment]
Fixed. Had to reconfigure and migrate LaTeXTool settings, then changed line 30 in ```LaTeXTools.sublime-settings``` to ```"texpath" : "$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin"```.

**Comment by skagrawal** [comment]
I was also facing this issue ...and solution given by TempSpas worked..thank you

**Comment by SimonSels** [comment]
Had the same problem upgrading to OS Sierra, and the solution provided by TempSas worked fine for me.

**Comment by r-stein** [comment]
The problem is that MacTex installs it files to different locations and they are not available in the PATH in Sublime Text. Therefore you must manually adapt the path if it is at such a location or you can try to install [Fix Mac Path]. 

[Fix Mac Path]:https://packagecontrol.io/packages/Fix%20Mac%20Path

**Comment by sunrise2075** [comment]
> Fixed. Had to reconfigure and migrate LaTeXTool settings, then changed line 30 in `LaTeXTools.sublime-settings` to `"texpath" : "$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin"`.

It works for me. My OS is macOS Mojave 10.14.
Many thanks!
